version: "3.8"

services:
  postres:
    image: postgres:12.4
    restart: always
    environment:
      POSTGRES_DB: Employee_Attendance_Database
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: changeme
      PGDATA: /var/lib/postgresql/data
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:4.26
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: your_mail@gmail.com
      PGADMIN_DEFAULT_PASSWORD: changeme
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - type: volume
        source: pgadmin-data
        target: /var/lib/pgadmin
    ports:
      - "8080:80"

volumes:
  db-data:
  pgadmin-data: